### PR TITLE
colors.scss folder added

### PR DESCRIPTION
**Pull request by mihrab34**

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### WOW! Readme file is very descriptive !!! Project looks! :+1:  

* Kindly recommended checking HTML markup with this [validator](https://validator.w3.org/#validate_by_upload)

Now it shows a lot of ERRORs in your project :(

errors

### You need to create next utilities:

### Colors

#### Background and text

The CSS files define:

* [ ] At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

* [ ] Classes to horizontally align text to the left, right or center
* [ ] At least five classes to set the font size of an element
* [ ] Three classes to set the font weight of an element (bold, normal, medium)

#### Border

* [ ] The CSS files define separate classes for border top, bottom, left, right, all border
* [ ] The border should span from 0 to 1rem
* [ ] The border should have classes for making box round
* [ ] The border should have a class defined to transform a box into a circle

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes.

**Comment by mihrab34** [comment]
The Color, Background, Text-align, Font and Border are all in the font.scss file

**Comment by shshamim63** [comment]
## Status :tada:  !! Approved !! :tada: 
___
Hi @Qoosim and @mihrab34 :wave: ,
Well done :clap: , You have met all the requirement that are actually needed to declare this project as complete. I can see separate files for separate task. Code looks neat and clean. 
___
##### This :+1: is from me. You can merge it and don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Pull request merged**
